version: '3.7'
services:
    app:
        build:
            context: ./
            dockerfile: ./docker/frankenphp/Dockerfile
        container_name: auth_service_app
        entrypoint: 'php artisan octane:frankenphp --workers=1 --max-requests=1'
        user: '${UID}'
        volumes:
            - './:/var/www'
            - /var/www/vendor/
            - /var/www/node_modules/
        ports:
            - '8701:8000'
            - '5173:5173'
        depends_on:
            - mysql
            - redis
    redis:
        image: 'redis:latest'
        container_name: auth_service_redis
        ports:
            - '6310:6379'
    mysql:
        image: 'mysql:8.3.0'
        platform: linux/x86_64
        container_name: auth_service_db
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: auth_service_db
        ports:
            - '8910:3306'
        volumes:
            - './data/mysql:/var/lib/mysql'
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
